### ISSUE TITLE
Expose internal/commands

### ISSUE THREAD

**Issue by nstogner** [open-policy-agent/conftest#209]
Lifting the `internal/` restriction on the `commands` pkg would allow for other cobra-based CLIs to embed `conftest` as sub commands.

**Comment by jpreese** [comment]
Which command(s) specifically are you looking to use?

**Comment by nstogner** [comment]
Possibly `conftest` in entirety as a sub-cmd of a larger toolkit, similar to how tools like `gcloud` used to embed `gcloud docker`.

**Comment by jpreese** [comment]
Do you have an immediate need for this? If not, I'd personally rather leave it as is, as it gives us more freedom to introduce changes as it's not exposed.

If you do, I'd love to hear/see your use case to look into it some.

**Comment by garethr** [comment]
I think aiming to have a specific interface for a future 1.0 release would be good, but I agree with @jpreese that should probably be explicit rather than just expose everything. Let's keep this thread open to track and discuss, but I'll close #210.

**Comment by johnharris85** [comment]
Re-raising this after the demo I did last week on the OPA community call (ref: https://github.com/open-policy-agent/opa/issues/2180#issuecomment-655659739) & discussion w/ @jpreese. As part of the tool we would like to embed the test and verify commands (output would probably also be useful for consistency etc... but not essential).

**Comment by jpreese** [comment]
@nstogner @johnharris85 the majority of the packages for `conftest` are now exposed! Resolving.

**Comment by luckoseabraham** [comment]
@jpreese - We have a use case to run conftest policy eval dynamically inside another golang application. 

The initial solution was to use conftest as a binary and run it as an exec command or a step runner. But the issue https://github.com/open-policy-agent/conftest/issues/696 prevents us from doing this in an environment.

My application is also in go, I might has well import this as a module and run the TestRunner from my code. This way, I can easily version control and manage dependency changes.

But this is all blocked due to the internal package use. Since majority of the packages are already exposed, would you be open for a PR to expose `internal/runner/test.go` as well ?

**Comment by Zest-nikunj** [comment]
+1

**Comment by luckoseabraham** [comment]
Yes @jpreese That is correct. We just need the `runner` package.

**Comment by luckoseabraham** [comment]
Would you be open to a PR ?

**Comment by jpreese** [comment]
@luckoseabraham @Zest-nikunj I'll be working in https://github.com/open-policy-agent/conftest/pull/697
