### ISSUE TITLE
Support XDG Specification for Plugin Directory

### ISSUE THREAD

**Issue by 06kellyjac** [open-policy-agent/conftest#264]
It's fantastic that plugins are now supported but it's a shame that it's lead to more homedir clutter on my machine.
It'd be great if the plugins were moved to `XDG_DATA_HOME` and the cache to `XDG_CACHE_HOME`, and any future global config files go into `XDG_CONFIG_HOME`

**Comment by Blokje5** [comment]
Great suggestion. `XDG_DATA_HOME` at the moment would make sense as the plugins are "installed" into that location. We do not maintain a configuration file of which plugins have been downloaded so we cannot retrigger a download, so the `XDG_CACHE_HOME` does not make sense.

**Comment by jpreese** [comment]
@Blokje5 @06kellyjac 

After https://github.com/open-policy-agent/conftest/pull/400 is completed, was going to take a look at this next.

I think we should be able to detect if `$XDG_DATA_HOME` or `$XDG_DATA_DIRS`, and if so, use that as the location to store the plugins.

`$XDG_DATA_HOME` seems the most appropriate for where plugins should be downloaded to. While we refer to the plugin dir as a cache, it feels more like an installation folder. 
[ Reference discussion on `$XDG_DATA_HOME` ] : https://github.com/helm/helm/issues/7206 

Additional consideration would be the `$XDG_DATA_DIRS` variable. If `$XDG_DATA_HOME` is not set, but `XDG_DATA_DIRS` is, we would parse that variable. 
[ Reference discussion on `$XDG_DATA_DIRS` and priority ] : https://github.com/KhronosGroup/Vulkan-Loader/issues/245

This would result in the following priority order and behavior:

1. If `$XDG_DATA_HOME` is set, the plugins are put in `$XDG_DATA_HOME/conftest/plugins`

1. If `$XDG_DATA_HOME` is _not_ set, but `$XDG_DATA_DIRS` _is_ set, iterate through `$XDG_DATA_DIRS` in the order they appear for `$dir/conftest/plugins`

1. If neither `$XDG_DATA_HOME` or `$XDG_DATA_DIRS` is set, plugins will be at `$HOME/conftest/plugins`

I would also like to introduce new commands:

- `conftest plugin cache` - Print the location of the plugin cache that is currently being looked at. This value would change based on how the `XDG_` variables are set and would be incredibly useful for troubleshooting.

- `conftest plugin list` - List the currently installed plugins.

I also think it makes sense to update our plugin configuration YAML to include the source URL (or path on disk) it came from for when we start talking about needing to re-download plugins automatically and checking for version updates.

Does all of this sound OK? Before this issue I have honestly not heard of the `XDG_` spec so this is all how I currently understand the spec to work, but I may be misunderstanding.

**Comment by 06kellyjac** [comment]
@jpreese All that sounds really good. You have a much better grasp of the XDG spec than the majority of people I see arguing about it :sweat_smile: 

I'd add that with the priority order and behavior if `$XDG_XYZ` is set but the directory doesn't actually exist it's probably best to log an error for the user & fall back to the next one?

Also the `conftest plugin cache` command sounds great, sometimes it can be a nightmare to tell where the hell a program is looking for things.
I'd say maybe it'd be better named as `conftest plugin location` as it avoids the confusion between `$XDG_CACHE_HOME` and `$XDG_DATA_HOME` & also reading it without context could look like a command to somehow cache your plugins?

**Comment by jpreese** [comment]
> I'd add that with the priority order and behavior if `$XDG_XYZ` is set but the directory doesn't actually exist it's probably best to log an error for the user & fall back to the next one?

In this context, is the directory the plugin directory or the directory defined in `$XDG_XYZ`? In the event that the plugin directory does not exist, to me, that would just mean no plugins are installed. `plugin install` would add the directory.

If the `$XDG_XYZ` directory _itself_ does not exist, I would vote for hard erroring. If the data in that variable isn't good, then I would pressure the user to remove or fix it.

> I'd say maybe it'd be better named as conftest plugin location as it avoids the confusion between $XDG_CACHE_HOME and $XDG_DATA_HOME & also reading it without context could look like a command to somehow cache your plugins?

I think that's a fair argument. Location does make sense to me. I'll look at some other tools that support this behavior and see what they end up calling it.

**Comment by 06kellyjac** [comment]
> In this context, is the directory the plugin directory or the directory defined in $XDG_XYZ?
Yeah the `$XDG_DATA_HOME` dir itself (etc). Hard erroring works for me too. Knowing I've messed up and my `~/.local/share/` dir has dissapeared would be nice to know & I don't want to have to move them from wherever they end up going back to the actual location I wanted once I re-make the dir.

**Comment by Blokje5** [comment]
Thanks for looking into this @jpreese. I must admit that I completely lost track of the issue. 

On your suggestions:
I agree with the priority order. Providing an error on a misconfigured `XDG_` variable makes sense if the variables are set to incorrect values. But I am unsure if we need a `conftest plugin location` command. I am not sure if a command just for debugging Conftest has added value as part of the CLI. I would propose one of the following alternatives:

1. Include the location on disk in the `conftest plugin list` command. We could provide flags to control the output.
2. Start applying trace logging in conftest, controlled with an environment variable. E.g. if I am debugging issues in Terraform i'll use `TF_LOG=TRACE` to figure out what is going wrong. This might be nice to have anyway.

**Comment by jpreese** [comment]
#1 sounds good to me. I initially hesitated to add it into the same command, because always printing the path seemed noisy to me. The plugin dir should never really change unless you're messing around with variables. 

Adding some sort of flag to `list` to show more information about the found plugins, including its location, sounds like a good approach.

**Comment by smcv** [comment]
Drive-by comment because I happened to see this referenced elsewhere (I have no idea what this piece of software is or what it does).

The specification is: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

> If $XDG_DATA_HOME is set, the plugins are put in $XDG_DATA_HOME/conftest/plugins

The spec defines a default for $XDG_DATA_HOME, which is $HOME/.local/share. If you use the XDG basedir spec like that, then people will usually expect that dropping plugins into ~/.local/share/conftest/plugins (with XDG_DATA_HOME left unset) will also work.

> If $XDG_DATA_HOME is not set, but $XDG_DATA_DIRS is set, iterate through $XDG_DATA_DIRS in the order they appear for $dir/conftest/plugins

Similarly, the spec defines a default for $XDG_DATA_DIRS, which is /usr/local/share:/usr/share. People will usually expect /usr/local/share/conftest/plugins and /usr/share/conftest/plugins to work when XDG_DATA_DIRS is unset.

It's OK to search additional, app-specific locations before, after or even during the XDG path search, if you want to do that. For example, you might have a search path like this:

* Standard: $XDG_DATA_HOME/conftest/plugins, using ~/.local/share if XDG_DATA_HOME is unset
* App-specific: ~/.conftest/plugins
* App-specific: ~/conftest/plugins
* Standard: $dir/conftest/plugins for each $dir in XDG_DATA_DIRS, using /usr/local/share:/usr/share if unset
* App-specific: ${prefix}/share/conftest/plugins, even if ${prefix} is neither /usr/local/share nor /usr/share

When you have found a directory containing your data, it's up to you whether to continue to read other locations or not. One common interpretation (which is often the most useful one) is to continue to read the other directories in the search path, but ignore anything that has the same name as a file found in a higher-priority search path entry. For instance, desktop environments look for applications in XDG_DATA_DIRS/applications. If the XDG variables are unset or at their default values, ~/.local/share/applications/gvim.desktop will take priority over /usr/local/share/applications/gvim.desktop or /usr/share/applications/gvim.desktop, and cause it to be ignored.

**Comment by jpreese** [comment]
XDG support was added in `0.22.0` of Conftest
