### ISSUE TITLE
Conftest and http.send

### ISSUE THREAD

**Issue by jpreese** [open-policy-agent/conftest#424]
From SO:

https://stackoverflow.com/questions/64178296/using-opa-http-send-with-conftest

**Comment by Blokje5** [comment]
I tried to reproduce the issue with the following policy (any input works here):

```
package main

available = http.send(
  {
  "method": "get",
  "url": "https://dog.ceo/api/breeds/image/random"
  }
)

deny[msg] {
    not available.body.status
    msg := "not available"
}

deny[msg] {
    available.body.status
    msg := sprintf("%v", [available.body.status])
}
```

The API if successful returns a JSON with a "status" key. The policy fails with the following result:

```
> conftest test -p examples/send/policy examples/send/input.yaml
FAIL - examples/send/input.yaml - success

2 tests, 1 passed, 0 warnings, 1 failure, 0 exceptions
```

and looking at the network traffic on my mac I can see packets going out. I'll comment on StackOverflow with a link to the issue and see if we can get the original poster involved.

**Comment by ac-obair** [comment]
Hi there OP here. I'd be good to understand where I've gone wrong. So what I'm acutally doing is getting a list of k8s versions from azure. 

This code as-is returns the list I need from the opa repl but packets never leave my interface with `conftest`. I was then hoping to import this so that it could be used when `conftest test` and `conftest verify` by using `import data.aks.versions as supported_versions` in another file which parses out the version that we're using and ensures it hasn't fell off the bottom.

```rego
package aks

import data.token as auth

# temp repopulate token with az account get-access-token > token/data.json
subscriptionid  = auth.subscription
authorisation   = sprintf("%s %s", [auth.tokenType, auth.accessToken])
location        = "uksouth"

request["url"] = url {
    url := sprintf("https://management.azure.com/subscriptions/%s/providers/Microsoft.ContainerService/locations/%s/orchestrators?api-version=2019-04-01&resource-type=managedClusters", [subscriptionid, location])
}

headers = {
    "Content-Type": "application/json",
    "Authorization": authorisation,
    "Accept": "application/json"
}

available_versions = http.send(
  {
  "method": "get",
  "url": request.url,
  "headers": headers
  }
)

versions[supported] {
     response := available_versions.body[_]
     some version
     not response.orchestrators[version].isPreview
     supported := response.orchestrators[version].orchestratorVersion
}
```

**Comment by jpreese** [comment]
```rego
package main

subscriptionid := "subscriptionid"
location := "location"

request["url"] = url {
    url := sprintf("https://management.azure.com/subscriptions/%s/providers/Microsoft.ContainerService/locations/%s/orchestrators?api-version=2019-04-01&resource-type=managedClusters", [subscriptionid, location])
}

headers = {
    "Content-Type": "application/json",
    "Accept": "application/json"
}

available_versions = http.send(
  {
  "method": "get",
  "url": request.url,
  "headers": headers
  }
)

deny[msg] {
    msg := available_versions.body[_]
}
```

Is working for me as well, at least in making an HTTP call out:

```bash
Error: running test: get test result: running deny rules: run query: run query: rule missing msg field: map[code:SubscriptionNotFound message:The subscription 'subscriptionid' could not be found.]
```

@ac-obair are you defining a `deny` , `warn`, or `violation` rule anywhere? Conftest uses these rule names as entry points.

If you copy/paste my Rego above, and run it through Conftest you should get the same error.

```bash
conftest test file_doesnt_matter.yaml -p rego_from_above.rego
```

**Comment by ac-obair** [comment]
I am using a deny, if you refer back to my SO post, I'm importing versions as a data doc, and using that to evaluate my deny. 

Something like this: 
```rego
deny[msg] {
    current_version = "1.17.11"
    not versions[current_version]
    msg := sprintf("%v is a deprecated aks version", [current_version])
} 
```
Same issue for me however, this is why I asked if I was using imports correctly and I'd expect the entrypoint of deny to fire when and build versions list once that line is evaluated. I've moved the deny to the same fine and removed the import, same issue. I get a deny regardless of the `current_version` which looks to me like `versions` is empty rather than the version just not being in there. However it isn't empty from the opa repl once the code is executed there.

I can reproduce your missing token message using that code. But executing successfully still gives me the result I was having when I originally made the SO post. I'll see if I can use some combination of the two to get it working this afternoon. It still looks to me like there's something different happening between the opa repl and the conftest run.

**Comment by jpreese** [comment]
An example that mimics your current setup as close as possible would definitely be appreciated, I think there's something that we're missing. I threw together a quick example using a real API, putting the request in a different package, importing it, and returning an error:

Inside of a single folder:

**api.rego**
```rego
package api

request["url"] = url {
    url := "https://petstore.swagger.io/v2/user/admin"
}

headers = {
    "Content-Type": "application/json",
    "Accept": "application/json"
}

available_versions = http.send(
  {
    "method": "get",
    "url": request.url
  }
)
```

***rule.rego***
```rego
package main

import data.api

deny[msg] {
    api.available_versions.body.type == "error"
    msg := api.available_versions.body.message
}
```

**foo.yaml**
_this is just a blank file_

```bash
λ conftest test foo.yaml -p .
FAIL - foo.yaml - User not found

1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions
```

**Comment by ac-obair** [comment]
```rego
> x = {"a","b","c"}
Rule 'x' defined in package repl. Type 'show' to see rules.
> x == set()
false
>
```
I think we can all agree that `x != set()` here. 

As I've been saying, removing the import for this example, if I use this code which is just using a simple token from az cli right now, but will eventually be a service principal:
```rego
package main

import input as hcl
import data.token as auth

subscriptionid  = auth.subscription
authorisation = sprintf("%s %s", [auth.tokenType, auth.accessToken])
location      = "uksouth"

request["url"] = url {
    url := sprintf("https://management.azure.com/subscriptions/%s/providers/Microsoft.ContainerService/locations/%s/orchestrators?api-version=2019-04-01&resource-type=managedClusters", [subscriptionid, location])
}

headers = {
    "Content-Type": "application/json",
    "Authorization": authorisation,
    "Accept": "application/json"
}

available_versions = http.send(
  {
  "method": "get",
  "url": request.url,
  "headers": headers
  }
)

versions[supported] {
     response := available_versions.body[_]
     some version
     not response.orchestrators[version].isPreview
     supported := response.orchestrators[version].orchestratorVersion
}

deny[msg] {
    versions == set()
    msg := sprintf("%v is a deprecated aks version", [versions])
}
```
Gives me 
```rego
conftest test main.tf -p aks.rego
FAIL - main.tf - set() is a deprecated aks version

1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions
```
So right now my `versions == set()`. Which I'm assuming means versions is empty. 

If I take that exact snippit and paste it into the repl:
```rego
> import data.token as auth
>
> # repopulate token with az account get-access-token > token/data.json
> subscriptionid  = auth.subscription
Rule 'subscriptionid' defined in package repl. Type 'show' to see rules.
> authorisation = sprintf("%s %s", [auth.tokenType, auth.accessToken])
Rule 'authorisation' defined in package repl. Type 'show' to see rules.
> location      = "uksouth"
Rule 'location' defined in package repl. Type 'show' to see rules.
>
> request["url"] = url {
|     url := sprintf("https://management.azure.com/subscriptions/%s/providers/Microsoft.ContainerService/locations/%s/orchestrators?api-version=2019-04-01&resource-type=managedClusters", [subscriptionid, location])
| }
|
Rule 'request' defined in package repl. Type 'show' to see rules.
> headers = {
|     "Content-Type": "application/json",
|     "Authorization": authorisation,
|     "Accept": "application/json"
| }
|
Rule 'headers' defined in package repl. Type 'show' to see rules.
> available_versions = http.send(
|   {
|   "method": "get",
|   "url": request.url,
|   "headers": headers
|   }
| )
|
Rule 'available_versions' defined in package repl. Type 'show' to see rules.
> versions[supported] {
|      response := available_versions.body[_]
|      some version
|      not response.orchestrators[version].isPreview
|      supported := response.orchestrators[version].orchestratorVersion
| }
|
Rule 'versions' defined in package repl. Type 'show' to see rules.
> versions
[
  "1.16.13",
  "1.16.15",
  "1.17.9",
  "1.17.11",
  "1.18.6",
  "1.18.8"
]
> versions == set()
false
```
Versions is not empty and `versions == set()` if false. Because the contents of versions is:
```
[
  "{\"1.16.13\", \"1.16.15\", \"1.17.11\", \"1.17.9\", \"1.18.6\", \"1.18.8\"}"
]
```
Taking this logic and running the deny rule for 1.15.11 which is deprecated and 1.17.11 which isn't we get 
```rego
deny[msg] {
    current_version := "1.17.11"
    not versions[current_version]
    msg := sprintf("%v is a deprecated aks version", [current_version])
}
```
```
Rule 'deny' defined in package repl. Type 'show' to see rules.
> deny
[
  "1.15.11 is a deprecated aks version"
]
```
Again this is only working from the repl. Conftest test always comes back with `versions == set()` and as far as I can tell no packets leave my interface, but your examples are giving me a consistent result with what you're seeing. Which means at least on some runs packets are leaving my interfaces with `conftest test` if not every time.

I am using tcpdump and filtering on `management.azure.com`. I get no packets from `conftest test` however from `opa run` repl I consistently see the successful circuit setup, data exchange and tear down on each run. I'm _not_ saying I haven't missed something blatently obvious here but I can't explain why `versions == set()` is true from conftest and false from the opa repl.

**Comment by ac-obair** [comment]
I feex. https://gist.github.com/b0bu/67d60fc0dbc5a9ae36406188117dfb36 

The issue was `import data.token as auth`

`auth` was undefined, by extension subscirptionid was never populated. This was working in `opa run -b .` because of a slight difference in how the data document is structured. `data.token.stuff` was a thing which translated to `data.stuff` in conftest.

**Comment by jpreese** [comment]
Glad you got this figured out! 🎉
