### ISSUE TITLE
Negative amount of passed tests

### ISSUE THREAD

**Issue by jaspervdj-luminal** [open-policy-agent/conftest#464]
I'm seeing an issue where the number of passed tests is negative if
a policy returns more than one failure.  This using conftest at the
latest master, 9366d99990c3eeed8daa1e32206e8256d3162ef3.

This is a minimal example that reproduces the problem:

```
$ cat policy/main.rego
package main

failures = ["one", "two", "three"]

deny[resource_name] {
  resource_name = failures[_]
}
```

```
$ cat foo.json
{}
```

```
$ conftest test foo.json
FAIL - foo.json - main - one
FAIL - foo.json - main - two
FAIL - foo.json - main - three

1 test, -2 passed, 0 warnings, 3 failures, 0 exceptions
```

**Comment by shteou** [comment]
Interesting, I wonder what the expected behaviour is here.

It's possible for rules to emit multiple results, but I wonder if it's not possible to know how many logical successes to which this would correlate. It doesn't seem like this information would be available.

The current behaviour seems to assume each rule definition will emit only a single failure, but that there can be multiple distinct rules with the same name, each of which are expected to omit 0 or 1 results.

e.g.

```
package main

deny[msg] {
  input.foo == "one"
  msg = "one"
}

deny[msg] {
  input.foo == "two"
  msg = "two"
}
```

What would be the sanest behaviour? Should each rule definition allow a maximum of one success, if no failures or exceptions are emitted? I also wonder if, for consistency, the same logic should be applied to multiple rule definitions for the same rule name. i.e. the above would return exactly one success, or one to two failures.

**Comment by Blokje5** [comment]
I think there is an issue in what is considered a test case within conftest. A failure in this case indicates that the input fails that specific rule, while the number of tests actually counts the number of rego rules (or number of tests): a single partially defined deny rule split into multiple definitions counts as a single rule.

In this case the input would be 3 documents (e.g. 3 yaml files), there is one test, and in total there are 3 failures of the test and 0 passes. The total number of test cases is the `input * the number of tests`. To make this information a bit clearer we could extend the console output to include the test cases. In that way we can calculate the total successes by subtracting the failures from the test cases: `successes = test cases - failures`. The question is whether it is easy to find the `# of test cases`, without e.g. having to count the number of unique inputs within e.g. a multi document yaml file.

**Comment by Blokje5** [comment]
Ok after a bit of a deep dive into the issue:

## The problem

Rego evaluation returns the following potential results based on whether the rule passes/fails:
1. Empty result if success (even if there are multiple partial definitions of the same rule, e.g. multiple `deny` rules)
2. Results equal to the number of failures/warnings (e.g. a single failure results, even if there are multiple partial definitions of the same rule).

Due to the fact that success only returns a single results, even if multiple partial definitions of a rule pass, we can only. approximate the number of successes.

Currently the following definition is used for successes:

```
successes := ruleCount - (len(failures) + len(warnings) + len(exceptions))
```

Where ruleCount defines the total number of partial definitions (e.g. the number of instances of deny). This of course goes wrong when a single rule (like the above example) returns multiple results for a single input. In the example above, the ruleCount is 1 and the total number of failures is 3.

An alternative I tried is the following:

```
successes := (len(results) - (len(failures) + len(warnings) + len(exceptions))) * ruleCount
```

This does work for the above example, however this fails in the following situation:

```
$ cat policy/main.rego
package main

deny[resource_name] {
  resource_name ="one"
}

deny[resource_name] {
  false
  resource_name = "two"
}
```

which will incorrectly return:
```
$conftest test foo.json
FAIL - tmp/foo.json - main - one

1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions

```

In this case we expect the second partial definition of deny to be passed.

## Approaches to solve this problem:

1. Clearly document that a single partial definitions is expected to return a single result per input. Maybe we should even fail a test when an incorrect result would be returned, although this might be a bit harsh.
2. Find a way to allow multiple outputs and finding the correct number of successes. But this becomes quite hard when you account for situations with multiple partial definitions each returning multiple results. Also per failed result, currently we would print a single failure line, which might not be wanted.
3. Print both the number of results in the output and the number of tests:
```
2 rules, 1 test, 0 passed, 0 warnings, 1 failure, 0 exceptions
```

Where the test(s) indicates the number of results returned. 

I am inclined to go with option 1 here. We could additionally build in a check to prevent multiple inputs from rendering incorrect test successes by failing if we get an unexpected number of results.

However, if we find a method of correctly approximating the number of successes even in the case of multiple results that could be really interesting.

**Comment by fadao23** [comment]
Hello, @Blokje5  i'm a bit confused with this issue, I just make some tests with previous versions, and the 0.21.0 have the expected behaviour :

```
$ cat policy/main.rego
package main

failures = ["one", "two", "three"]

deny[resource_name] {
  resource_name = failures[_]
}
```

```
$ cat foo.json
{}
```

```
$ conftest -v
Version: 0.21.0
Commit: 125160d
Date: 2020-09-13T10:21:35Z
```

```
conftest test foo.json
FAIL - foo.json - one
FAIL - foo.json - two
FAIL - foo.json - three

3 tests, 0 passed, 0 warnings, 3 failures, 0 exceptions
```

So, what happen between 0.21.0 and 0.22.0 ?

**Comment by danielpacak** [comment]
I bumped into the same issue and negative pass counts are still there in v0.23.0

**Comment by jpreese** [comment]
All, I have a proposed fix available here: https://github.com/open-policy-agent/conftest/pull/527

It returns the expected results for all of the examples I saw in this thread and passes our current acceptance tests so we should be good.
