### ISSUE TITLE
Docker image for v0.23.0 release missing

### ISSUE THREAD

**Issue by nairb774** [open-policy-agent/conftest#473]
It looks like releasing the v0.23.0 docker image got missed when the latest release was done: https://hub.docker.com/r/openpolicyagent/conftest/tags

**Comment by jpreese** [comment]
We had a small hiccup with the credentials used to push to DockerHub. 

@tsandall if the original credentials that were set up for us are no longer valid for us, should we just issue a new set? Thoughts?

**Comment by tsandall** [comment]
@jpreese I just looked at the openpolicyagent/conftest DockerHub repo and noticed that unlike the gatekeeper and opa repos, there was no permission for the `openpolicyagentopaci` user in the conftest repo (it should minimally have read/write so that it can push). I've added the permission so maybe it will work now...can you kick the build and see if it works?

![image](https://user-images.githubusercontent.com/238885/105915261-805ee780-5ffd-11eb-83cb-40ef7f3ecf55.png)

**Comment by jpreese** [comment]
Brilliant! That was it. `v0.23.0` has been pushed. Thanks @tsandall 🎉

**Comment by nairb774** [comment]
Thanks!
