### ISSUE TITLE
can't install a plugin following the document

### ISSUE THREAD

**Issue by oke-py** [open-policy-agent/conftest#486]
I can't install the Kubernetes Conftest plugin following the [document](https://www.conftest.dev/plugins/).

```
$ conftest plugin install https://github.com/open-policy-agent/conftest/contrib/plugins/kubectl
Error: install: install from url: download plugin: client get: bad response code: 404
```

environment
- macOS Big Sur 11.2
- MacBook Air (M1, 2020)
- `conftest --version`

      Version: 0.23.0
      Commit: 6190ded
      Date: 2021-01-09T10:26:15Z

**Comment by jpreese** [comment]
Looks like it may just be documentation foul. Opened PR to update the documentation to a command that worked for me. The most notable change was adding `//` for including the subdirectory -- the `https` go-getter by default will download the full HTML of the target (in this case `kubectl`, rather than the backing `git` directory).

The following command should allow you to install the kubectl plugin:

```
conftest plugin install git://github.com/open-policy-agent/conftest//contrib/plugins/kubectl
```

https://github.com/open-policy-agent/conftest/pull/493
