### ISSUE TITLE
Test Custom Resources in kubernetes

### ISSUE THREAD

**Issue by AdheipSingh** [open-policy-agent/conftest#566]
- Hi Team, is it possible to test custom resources with conftest ? 
- I dont see any example for that, was wondering if its possible. 

Thanks

**Comment by boranx** [comment]
I was actually thinking the same for a while... We may consider treating it as a kind of [parser](https://github.com/open-policy-agent/conftest/tree/master/parser) where we could parse at least the first levels like _apiVersion, kind, spec_ etc...

**Comment by boranx** [comment]
I think we can apply the existing [kubernetes](https://github.com/open-policy-agent/conftest/blob/master/examples/kubernetes/policy/kubernetes.rego) example to any other CR that could have been created on a k8s cluster. the kubernetes parser is actually _yaml_ parser so that it should be able to parse given CR that's json/yaml

**Comment by jpreese** [comment]
> * Hi Team, is it possible to test custom resources with conftest ?
> * I dont see any example for that, was wondering if its possible.
> 
> Thanks

Yep! It's all just YAML, the contents of the YAML don't really matter.

**Comment by AdheipSingh** [comment]
Great !! ill give it a try.
Thank you :)  @jpreese @boranx
