### ISSUE TITLE
new SBOM parser

### ISSUE THREAD

**Issue by developer-guy** [open-policy-agent/conftest#623]
There is a concept called SBOM (Software Bill Of Materials), and there are various tooling around this[^1][^2][^3][^4] concept to generate it. There are several methods designed specifically for delivering SBOMs, including [SPDX (Software Package Data Exchange)](https://spdx.dev), [Software Identification (SWID) Tags](https://nvd.nist.gov/products/swid), and [Cyclone DX](https://cyclonedx.org).

Wouldn't be nice if we support validating these types of SBOM specs via rego-based policies in `conftest`.

[^1]: https://github.com/anchore/syft
[^2]:  https://github.com/spdx/spdx-sbom-generator
[^3]: https://github.com/tern-tools/tern
[^4]: https://github.com/kubernetes/release/tree/master/cmd/bom

cc: @luhring @nishakm @puerco 🥳🙋🏻‍♂️

**Comment by jalseth** [comment]
OK, after further reading I think the desired outcome of this would be to support the plaintext formats for the SBOMs in addition to their structured JSON/XML formats? If so that makes sense and I'd welcome PRs. It would also be good to open issues for each format that needs to be implemented (again with a link to the spec and/or examples) so that the work can be better tracked.

**Comment by developer-guy** [comment]
> OK, after further reading I think the desired outcome of this would be to support the plaintext formats for the SBOMs in addition to their structured JSON/XML formats?

Yeah, exactly. Let me explain it to you by giving an example, here is my thought about the SBOM validation belonging to SPDX.

Let's consider this repository for [SPDX examples.](https://github.com/spdx/spdx-examples/blob/master/example1/spdx/example1.spdx)

```shell
package main

denylist = ["openjdk"]

deny[msg] {
	input[i].Cmd == "from"
	val := input[i].Value
	contains(val[i], denylist[_])

	msg = sprintf("unallowed image found %s", [val])
}
```

**Comment by jalseth** [comment]
@developer-guy I'd imagine you'd want to use https://github.com/spdx/tools-golang to handle the parsing from the file into the struct. From there it isn't much work to plumb that to the OPA/Rego engine since it accepts an `interface{}` for input. I may work on adding this if I have time, but it would be great to receive a PR from the community!

**Comment by developer-guy** [comment]
@jalseth I'm a volunteer for doing this, may I take a look at it? Can you please assign it to me? 😍

**Comment by developer-guy** [comment]
for the other one we can use this https://github.com/CycloneDX/cyclonedx-go

**Comment by developer-guy** [comment]
friendly ping @jalseth

**Comment by jalseth** [comment]
@developer-guy I would welcome PRs! Please keep the SPDX and CycloneDX changes separate so they're easier to review.
