### ISSUE TITLE
conftest parse: allow JSON output format

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/conftest#684]
`conftest parse` currently prints the name of the file parsed before it goes on to print the JSON structure parsed from the input. In order to pipe the output of `conftest parse` into `jq`, `opa eval` or other tools dealing with JSON (or simply for copy-pasting into the Rego Playground), it would be useful if `conftest parse` provided and `--output json` option that printed only the JSON representation.

**Comment by jalseth** [comment]
Hi Anders, thanks for raising this issue! I agree the output should only include valid JSON for interoperability with other tools. Rather than omitting the file name altogether, what do you think about having the output be a JSON document containing an array of objects with `filePath` and `contents` fields? I expect most users only parse a single file at a time, so we could also have a `--include-filepath-single-files` flag (perhaps with a shorter/better name) that would default to `false` so that when parsing a single file, it would only include the JSON of the parsed configuration. What are your thoughts on this approach?

**Comment by anderseknert** [comment]
That sounds like a solid plan to me, @jalseth 👍

**Comment by jalseth** [comment]
The final implementation used a `map[filePath]config` structure rather than a list with `filePath` and `contents` fields. This change has been included in the latest release.

**Comment by anderseknert** [comment]
Fantastic! Thanks @jalseth 👍
